# Generated by Django 5.1.4 on 2024-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bindingemail',
            field=models.BooleanField(db_column='bindingEmail', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bindingtelegram',
            field=models.BooleanField(db_column='bindingTelegram', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegramuserid',
            field=models.CharField(db_column='telegramUserId', max_length=255, null=True),
        ),
    ]
